import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faTachometerAlt,
  faBook,
  faHourglassEnd,
  faCalculator,
  faUsers,
  faBuilding,
  faUniversity,
  faIndustry,
  faBookOpen,
  faQuestionCircle,
  faBars,
  faSyncAlt,
  faPlus,
  faTrash,
  faPenAlt,
  faPen,
  faFilePdf,
  faFileWord,
  faCode,
  faFileDownload,
  faSearch,
  faSquare,
  faUpload,
  faMapMarkerAlt,
  faCamera,
  faCircle,
  faTimes,
  faFont,
  faHandPaper,
  faUndo,
  faRedo,
  faLock,
  faLockOpen,
  faSlash,
  faImage,
  faExpand,
  faCompress,
  faCompressArrowsAlt,
  faExpandArrowsAlt,
  faChevronLeft,
  faChevronRight,
  faCaretLeft,
  faCaretRight,
  faCheck,
  faExclamationTriangle,
  faExclamation,
  faEye,
  faClipboardList,
  faListOl,
  faObjectGroup,
  faHome,
  faUser,
  faUserCircle,
  faArrowLeft,
  faArrowRight,
  faEdit,
  faSignOutAlt,
  faClone,
  faQuestion,
  faChartPie,
  faMinus,
  faFileExport,
  faDoorOpen,
  faSave,
  faEyeSlash,
  faArchive,
  faPenFancy,
  faFileSignature,
  faEuroSign,
  faCogs,
  faDatabase,
  faFileImage,
  faHardHat,
  faBoxOpen,
  faBug,
  faEllipsisV,
  faKiwiBird,
} from "@fortawesome/free-solid-svg-icons";

library.add(faTachometerAlt);
library.add(faBook);
library.add(faHourglassEnd);
library.add(faCalculator);
library.add(faCalculator);
library.add(faBuilding);
library.add(faUniversity);
library.add(faIndustry);
library.add(faBookOpen);
library.add(faQuestionCircle);
library.add(faBars);
library.add(faSyncAlt);
library.add(faPlus);
library.add(faTrash);
library.add(faPenAlt);
library.add(faPen);
library.add(faFilePdf);
library.add(faFileWord);
library.add(faCode);
library.add(faFileDownload);
library.add(faSearch);
library.add(faSquare);
library.add(faUpload);
library.add(faMapMarkerAlt);
library.add(faCamera);
library.add(faCircle);
library.add(faTimes);
library.add(faFont);
library.add(faHandPaper);
library.add(faUndo);
library.add(faRedo);
library.add(faLock);
library.add(faLockOpen);
library.add(faSlash);
library.add(faImage);
library.add(faExpand);
library.add(faCompress);
library.add(faCompressArrowsAlt);
library.add(faExpandArrowsAlt);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faCaretLeft);
library.add(faCaretRight);
library.add(faCheck);
library.add(faExclamationTriangle);
library.add(faExclamation);
library.add(faEye);
library.add(faClipboardList);
library.add(faListOl);
library.add(faObjectGroup);
library.add(faUsers);
library.add(faUser);
library.add(faUserCircle);
library.add(faHome);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faEdit);
library.add(faSignOutAlt);
library.add(faClone);
library.add(faQuestion);
library.add(faChartPie);
library.add(faMinus);
library.add(faFileExport);
library.add(faDoorOpen);
library.add(faSave);
library.add(faEyeSlash);
library.add(faArchive);
library.add(faPenFancy);
library.add(faFileSignature);
library.add(faEuroSign);
library.add(faCogs);
library.add(faDatabase);
library.add(faFileImage);
library.add(faHardHat);
library.add(faBoxOpen);
library.add(faBug);
library.add(faEllipsisV);
library.add(faKiwiBird);
