export default [
  {
    title: "Titre",
    id: "contact-secondaire-title",
    sectionId: "section-contact",
    subSectionId: "section-contact-contact-secondaire",
    type: "single-select",
    mandatory: true,
    value: "",
    options: {
      values: ["Mme", "M"],
    },
  },
  {
    title: "Prénom",
    id: "contact-secondaire-firstname",
    sectionId: "section-contact",
    subSectionId: "section-contact-contact-secondaire",
    type: "string",
    mandatory: true,
    value: "",
  },
  {
    title: "Nom de famille",
    id: "contact-secondaire-lastname",
    sectionId: "section-contact",
    subSectionId: "section-contact-contact-secondaire",
    type: "string",
    mandatory: true,
    value: "",
    documentation: "Nom de famille du contact secondaire",
  },
  {
    title: "Occupation",
    id: "contact-secondaire-occupation",
    sectionId: "section-contact",
    subSectionId: "section-contact-contact-secondaire",
    type: "single-select",
    mandatory: true,
    value: "",
    options: {
      values: ["Propriétaire", "Locataire"],
    },
  },
];
